console.log("Sasha's first console project");
var name1="Aditi";
console.log(name1);
var name2="Rao";
console.log(name2);
var name3=name1.concat(name2);
console.log(name3);
var x=9;
console.log(x);
var y=18;
console.log(y);
var z=x+y;
console.log(z);
 z=y-x;
console.log(z);
 z=y/x;
console.log(z);
 z=x*y;
console.log(z);